version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5002"
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db/testdb

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: